
import React from 'react';

export type LegalType = 'privacy' | 'terms' | 'cookies' | 'about' | null;

interface LegalModalProps {
  type: LegalType;
  onClose: () => void;
}

const LegalModal: React.FC<LegalModalProps> = ({ type, onClose }) => {
  if (!type) return null;

  const content = {
    about: {
      title: "About FitBitez",
      sections: [
        {
          h: "The Creator",
          p: "Hi, I'm Yash. I live in Bangalore. I'm a developer passionate about building AI-driven tools that make health and nutrition accessible to everyone."
        },
        {
          h: "Our Mission",
          p: "FitBitez was built to simplify the complex world of Indian nutrition. By combining Gemini AI with local data, we provide accurate calorie tracking and budget-friendly meal suggestions."
        },
        {
          h: "Other Work",
          p: "If you enjoy FitBitez, please check out my other application on the Play Store: 'SmartHealth AI' – your comprehensive health companion."
        }
      ]
    },
    privacy: {
      title: "Privacy Policy",
      sections: [
        {
          h: "Data Collection",
          p: "FitBitez collects food images and text descriptions provided by the user to perform nutritional analysis. These images are processed via Google Gemini AI."
        },
        {
          h: "Local Storage",
          p: "Your meal history and application preferences (like Dark Mode) are stored locally on your device. We do not maintain a central database of your personal meal logs."
        },
        {
          h: "Third Party Sharing",
          p: "Images are sent to Google's Generative AI services for analysis. We do not sell your personal data to advertisers or third-party brokers."
        }
      ]
    },
    terms: {
      title: "Terms of Use",
      sections: [
        {
          h: "AI Accuracy Disclaimer",
          p: "Nutritional data provided is an approximation generated by Artificial Intelligence. FitBitez is not a medical device and should not be used for critical healthcare decisions."
        },
        {
          h: "Usage Policy",
          p: "Users are responsible for the content they upload. Uploading non-food items or harmful content may result in service restrictions."
        },
        {
          h: "Service Availability",
          p: "We strive for 100% uptime, but API availability depends on third-party providers. We reserve the right to modify or discontinue features at any time."
        }
      ]
    },
    cookies: {
      title: "Cookie & Data Policy",
      sections: [
        {
          h: "How we use Cookies",
          p: "We use 'Local Storage' instead of traditional cookies to remember your theme settings and save your meal logs without requiring an account."
        },
        {
          h: "Why it matters",
          p: "This allows the app to work faster and protects your privacy by keeping your personal health history on your own machine."
        }
      ]
    }
  }[type];

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-8">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-slate-950/60 backdrop-blur-md transition-opacity"
        onClick={onClose}
      ></div>
      
      {/* Modal Content */}
      <div className="relative bg-white dark:bg-slate-900 w-full max-w-2xl max-h-[80vh] rounded-[2.5rem] shadow-2xl border border-gray-100 dark:border-slate-800 overflow-hidden flex flex-col animate-in zoom-in-95 fade-in duration-300">
        <div className="p-8 border-b border-gray-50 dark:border-slate-800 flex justify-between items-center sticky top-0 bg-white/80 dark:bg-slate-900/80 backdrop-blur-md z-10">
          <h2 className="text-2xl font-black text-gray-900 dark:text-white tracking-tight">{content.title}</h2>
          <button 
            onClick={onClose}
            className="p-2 rounded-full hover:bg-gray-100 dark:hover:bg-slate-800 text-gray-400 transition-colors"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        
        <div className="p-8 overflow-y-auto space-y-8 custom-scrollbar">
          {content.sections.map((s, i) => (
            <div key={i} className="space-y-3">
              <h3 className="text-emerald-600 dark:text-emerald-400 font-black text-sm uppercase tracking-widest">{s.h}</h3>
              <p className="text-gray-600 dark:text-slate-400 leading-relaxed font-medium">{s.p}</p>
            </div>
          ))}
          <div className="pt-8 text-center border-t border-gray-50 dark:border-slate-800">
            <p className="text-gray-400 dark:text-slate-500 text-xs font-bold uppercase tracking-tighter">Last Updated: December 2025</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LegalModal;
